FROM python:3.8

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /insurance

# Install dependencies
COPY requirements.txt /insurance/
RUN pip install -r requirements.txt

# Copy project
COPY . /insurance/

# CMD ["uvicorn", "main:app", "--host", "127.0.0.1", "--port", "8000"]